openapi: 3.0.0
info:
  title: Web Platform API
  description: API web platform for Hikoo backend server
  version: 1.0.0
schemes:
  - http
paths:
  /allgps:
    get:
      summary: Returns list of hiker, events, and broadcast.
      responses:
        '200':
          description: A JSON array of data location and its info
          content:
            application/json:
              schema: 
                type: object
                properties:
                  location:
                    type: string
                    description: latitude and longitude value
                  point_type:
                    type: string
                    description: map legend information
                    enum: ['hiker', 'event', 'alert']
                  event_id:
                    type: integer
                    description: event id number
                  event_type:
                    type: string
                    description: event type name
                    example: Blocked Path
                  alert_id: 
                    type: integer
                    description: alert id number
                  alert_level:
                    type: string
                    description: alert level name
                    example: WARNING
                  timestamp:
                    type: string
                    description: time creation of the point
  /events:
    get:
      summary: Return list of event
      produces:
        - application/json
      responses:
        '200':
          description: A JSON array of event data
          schema:
            type: object
            properties:
                hike_id:
                  type: integer
                  description: id of the hike
                permit_name:
                  type: string
                  description: permit name related to hike
                location:
                  type: string
                  description: latitude and longitude value
                radius:
                  type: integer
                  description: radius event to broadcast in km. Except -1 means to everyone in mountain
                alert_id: 
                  type: integer
                  description: alert id number
                alert_level:
                  type: string
                  description: alert level name
                  example: WARNING
                event_id:
                  type: integer
                  description: event id number
                event_type:
                  type: string
                  description: event type name
                  example: Blocked Path
                event_info:
                  type: string
                  description: additional information of the event
                event_time:
                  type: string
                  description: time the event is reported
                ttl:
                  type: string
                  description: time to live before event is obsolete
                reporter:
                  type: string
                  description: id of user who report the event
    post:
      summary: Create a new event
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: User body
          required: true
          schema:
            type: object
            properties:
              hike_id:
                type: integer
                description: id of the hike
              location:
                type: string
                description: latitude and longitude value
              radius:
                type: integer
                description: radius event to broadcast in km. Except -1 means to everyone in mountain
              alert_id: 
                type: integer
                description: alert id number
              event_id:
                type: integer
                description: event id number
              event_info:
                type: string
                description: additional information
              event_time:
                type: string
                description: time the event is reported
              ttl:
                type: string
                description: time to live before event is obsolete
              reporter:
                type: integer
                description: id of user who report the event
      responses:
        '200':
          description: Created a new event
  /alerts:
    get:
      summary: Returns list of alert
      produces:
        - application/json
      responses:
        '200':
          description: A JSON array of alert data
          schema: 
            type: object
            properties:
              permit_id:
                type: integer
                description: id of the permit
              permit_name:
                type: string
                description: name of the permit
              location:
                type: string
                description: latitude and longitude value
              radius:
                type: integer
                description: radius event to broadcast in km. Except [-1] means to everyone in permit_id
              alert_id: 
                type: integer
                description: alert id number
              alert_level:
                type: string
                description: alert level name
                example: WARNING
              event_id:
                type: integer
                description: event id number
              event_type:
                type: string
                description: event type name
                example: Blocked Path
              event_info:
                type: string
                description: additional information
              event_time:
                type: string
                description: time the alert is created
              ttl:
                type: string
                description: time to live before event is obsolete
              station_id:
                type: integer
                description: stations id number
              station:
                type: string
                description: station responsible for the event
    post:
      summary: Create a new alert
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: User body
          required: true
          schema:
            type: object
            properties:
              permit_id:
                type: integer
                description: id of the permit
              location:
                type: string
                description: latitude and longitude value
              radius:
                type: integer
                description: radius event to broadcast in km. Except -1 means to everyone in mountain
              alert_id: 
                type: integer
                description: alert id number
              event_id:
                type: integer
                description: event id number
              event_info:
                type: string
                description: additional information
              event_time:
                type: string
                description: time the alert is created
              ttl:
                type: string
                description: time to live before event is obsolete
              origin_source:
                type: integer
                description: origin of the event if this alert is from event reported. CAN BE NULL
              creator:
                type: integer
                description: id of the station who made the alert
      responses:
        '200':
          description: Created new alert
