openapi: 3.0.0
info:
  title: Web Platform API
  description: API web platform for Hikoo backend server
  version: 1.0.0
paths:
  /allgps:
    get:
      summary: Returns list of hiker, events, and broadcast.
      responses:
        '200':
          description: A JSON array of data location and its info
          content:
            application/json:
              schema: 
                type: object
                properties:
                  location:
                    type: string
                    description: latitude and longitude value
                  point_type:
                    type: string
                    description: map legend information
                    enum: ['hiker', 'event', 'alert']
                  event_id:
                    type: integer
                    description: event id number
                  event_type:
                    type: string
                    description: event type name
                    example: Blocked Path
                  alert_id: 
                    type: integer
                    description: alert id number
                  alert_level:
                    type: string
                    description: alert level name
                    example: WARNING
                  timestamp:
                    type: string
                    description: time creation of the point
  /events:
    get:
      summary: Return list of event
      responses:
        '200':
          description: A JSON array of event data
          content:
            application/json:
            schema:
              type: object
              properties:
                  mountain_id:
                    type: integer
                    description: id of the mountain
                  mountain:
                    type: string
                    description: name of the mountain
                  location:
                    type: string
                    description: latitude and longitude value
                  radius:
                    type: integer
                    description: radius event to broadcast in km. Except -1 means to everyone in mountain
                  event_id:
                    type: integer
                    description: event id number
                  event_type:
                    type: string
                    description: event type name
                    example: Blocked Path
                  alert_id: 
                    type: integer
                    description: alert id number
                  alert_level:
                    type: string
                    description: alert level name
                    example: WARNING
                  timestamp:
                    type: string
                    description: time creation of the point
                  station_id:
                    type: integer
                    description: stations id number
                  station:
                    type: string
                    description: station responsible for the event
    post:
      summary: Create a new event
      requestBody:
        required: true
        content:
          application/json:
              schema:
                type: object
                properties:
                  mountain_id:
                    type: integer
                    description: id of the mountain
                  location:
                    type: string
                    description: latitude and longitude value
                  radius:
                    type: integer
                    description: radius event to broadcast in km. Except -1 means to everyone in mountain
                  event_id:
                    type: integer
                    description: event id number
                  alert_id: 
                    type: integer
                    description: alert id number
                  reporter:
                    type: integer
                    description: id of user who report the event
                  timestamp:
                    type: string
                    description: broadcast time
      responses:
        '201':
          description: Created new event
  /alert:
    get:
      summary: Returns list of alert
      responses:
        '200':
          description: A JSON array of alert data
          content:
            application/json:
              schema: 
                type: object
                properties:
                  mountain_id:
                    type: integer
                    description: id of the mountain
                  mountain:
                    type: string
                    description: name of the mountain
                  location:
                    type: string
                    description: latitude and longitude value
                  radius:
                    type: integer
                    description: radius event to broadcast in km. Except -1 means to everyone in mountain
                  event_id:
                    type: integer
                    description: event id number
                  event_type:
                    type: string
                    description: event type name
                    example: Blocked Path
                  alert_id: 
                    type: integer
                    description: alert id number
                  alert_level:
                    type: string
                    description: alert level name
                    example: WARNING
                  timestamp:
                    type: string
                    description: broadcast time
                  station_id:
                    type: integer
                    description: stations id number
                  station:
                    type: string
                    description: station responsible for the event
    post:
      summary: Create a new alert
      requestBody:
        required: true
        content:
          application/json:
              schema:
                type: object
                properties:
                  mountain_id:
                    type: integer
                    description: id of the mountain
                  location:
                    type: string
                    description: latitude and longitude value
                  radius:
                    type: integer
                    description: radius event to broadcast in km. Except -1 means to everyone in mountain
                  event_id:
                    type: integer
                    description: event id number
                  alert_id: 
                    type: integer
                    description: alert id number
                  timestamp:
                    type: string
                    description: broadcast time
      responses:
        '201':
          description: Created new event
