# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x
    - name: npm install
      run: npm install --no-save
    - name: npm run build
      run: npm run build
    
