name: CI

on:
  push:
    branches:
      - develop
      - feature/cicd

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install --no-save
        run: |
          npm install --no-save

      - name: npm run prebuild
        run: |
          npm run prebuild

      - name: npm run prebuild
        run: |
          npm run prebuild
